<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-418NQCC" ignored="2" name="Test(failed)" tests="6" failures="1" timestamp="21 Nov 2022 11:22:44 GMT" time="0.187" errors="0">
  <testcase name="test3" time="0.031" classname="org.test.rerun.RerunTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.016" classname="org.test.rerun.RerunTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="org.test.rerun.RerunTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="org.test.rerun.RerunTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="org.test.rerun.RerunTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.015" classname="org.test.rerun.RerunTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.test.rerun.RerunTest.test3(RerunTest.java:22)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="org.test.rerun.RerunTest">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="org.test.rerun.RerunTest">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test(failed) -->
